### ISSUE TITLE
Multiple components in REPL

### ISSUE THREAD

**Issue by stubailo** [sveltejs/svelte.technology#12]
I was going to create a REPL example with a recursive tree of data, but this isn't possible without having multiple components. I guess Svelte doesn't support multiple components in one file?

**Comment by proyb6** [comment]
Nice to see you here from MeteorJS!

**Comment by Rich-Harris** [comment]
Not in one file, no. I've thought about two ways of handling this – allowing multiple component editors (similar to how http://rollupjs.org/ allows multiple modules), or allowing components to be imported from gist.github.com (since that's where they're being stored), with something like this:

```html
<Widget/>

<script>
  import Widget from 'gist:123xyz';

  export default {
    components: { Widget }
  };
</script>
```

The second is probably a bit easier and more flexible.

**Comment by stubailo** [comment]
My dream would be if I could make a multi-file gist, and import between the files in the gist. 🎉

**Comment by Rich-Harris** [comment]
> My dream would be if I could make a multi-file gist, and import between the files in the gist. 🎉

[Et voila!](https://svelte.technology/repl?version=1.13.5&example=nested-components)

**Comment by stubailo** [comment]
incredible!
