### ISSUE TITLE
The introduction tutorial doesn't work

### ISSUE THREAD

**Issue by ericandrewlewis** [sveltejs/svelte.technology#187]
I'm following along with [this introduction](https://svelte.technology/guide), where I'm instructed to install `svelte-cli` globally. When I do this, I notice an unmet peer dependency of `svelte`

```
↪ npm install -g svelte-cli
/Users/ericlewis/.nvm/versions/node/v6.6.0/bin/svelte -> /Users/ericlewis/.nvm/versions/node/v6.6.0/lib/node_modules/svelte-cli/bin.js
/Users/ericlewis/.nvm/versions/node/v6.6.0/lib
├── UNMET PEER DEPENDENCY svelte@*
└── svelte-cli@2.0.0

npm WARN svelte-cli@2.0.0 requires a peer of svelte@* but none was installed.
```

When I try to run the `svelte compile` bit soon after, I get an error

```
↪ svelte compile --format iife HelloWorld.html > HelloWorld.js
module.js:457
    throw err;
    ^

Error: Cannot find module 'svelte'
```

Thanks for svelte, excited to be trying it out :)

**Comment by Rich-Harris** [comment]
Hey @ericandrewlewis, good to see you around these parts.

Mea culpa: I released version 2 of svelte-cli recently with `svelte` in `peerDependencies`, because we'd encountered problems with people trying to update Svelte in their projects and it not working because Yarn and npm would 'helpfully' keep the old version inside `svelte-cli/node_modules`. But this is worse. I just released 2.0.1 which reverses that decision.

The docs need to better reflect this, but using the CLI isn't all that recommended for anything beyond simple experiments, since you lose certain advantages (such as deduplicating helpers between components, which has a noticeable impact once your app has more than a couple). It's better to follow the guidelines in [this blog post](https://svelte.technology/blog/the-easiest-way-to-get-started) (though we have some ideas for improving the CLI experience, such as adding a bundle mode).

Will close this now that 2.0.1 is out.
