### ISSUE TITLE
How about pre- and post-processor support (Sass, PostCSS, Pug)?

### ISSUE THREAD

**Issue by lunelson** [sveltejs/svelte.technology#190]
This is very impressive and exciting; I'm wondering about integrating pre-/post-processing support: 

1. CSS pre-processors such as Sass, LESS, and Stylus could be invoked by adding a `lang` attribute on the `style` tag (similarly to how `.vue` single-file components manage it), and a PostCSS process for the `style` tag (e.g. to run autoprefixer, if nothing else) would be advisable for CSS in any case; plus

2. an HTML pre-processor like pug could be applied to the whole file, so that rather than `App.html` one simply writes `App.pug`. This is also possible with `.vue` files and does not seem to interfere with Vue's syntax.

Does that seem viable?

**Comment by Rich-Harris** [comment]
This is possible via `svelte.preprocess`, which as of five minutes ago is documented here: https://svelte.technology/guide#preprocessing

It's a low-level function by design — it doesn't know anything about Pug or Sass etc, but it gives you the tools you need to add support for those languages. The hope is that in future we'll have packages that take care of all the boilerplate:

```js
import sass from 'svelte-preprocess-sass'; // does not yet exist

// this would typically be used with rollup-plugin-svelte or svelte-loader,
// though you can also use `svelte.preprocess` directly
const buildToolIntegrationOptions = {
  preprocess: {
    style: sass
  }
};
```

**Comment by lunelson** [comment]
Great! Thanks!
