### ISSUE TITLE
Invalid store example

### ISSUE THREAD

**Issue by tivac** [sveltejs/svelte.technology#307]
https://svelte.technology/guide#the-basics

The supplied example code

```js
import { Store } from 'svelte/store.js';

const store = new Store({
	name: 'world'
});

const { name } = store.get(); // 'world'

store.on('state', ({ current }) => {
	console.log(`hello ${current.name}`);
}); // 'hello world'

store.set({ name: 'everybody' }); // 'hello everybody'
```

implies that two messages will be logged, "hello world" and "hello everybody".

This is wrong though, the `state` listener only gets called for changes that occur **after** it is attached so it never sees the original state.

[REPL repro](https://svelte.technology/repl?version=2.7.2&gist=176e0d25a772d628ab11cabf39eda4c1)

FWIW I'd **love** if this example did work as written, but I don't see any support in the [generic `.on()` handler](https://github.com/sveltejs/svelte/blob/master/src/shared/index.js#L70-L80) that would let the parent object know when a new listener is attached for a state.

**Comment by Rich-Harris** [comment]
Ah, yeah. This is because you used to do this...

```js
store.observe('name', name => {
  console.log(`hello ${name}`);
});
```

...and that *did* fire immediately. I must have missed that comment when updating the docs.

`observe` was removed in v2 because it's only useful to a subset of people but adds non-trivial weight to a component. The `state` and `update` events (and their lifecycle hook counterparts) are more powerful and the code is more concise. But since `observe` *is* useful, for the reason you identify, it's still available via `svelte-extras`:

```js
import { Store } from 'svelte/store.js';
import { observe } from 'svelte-extras';

class MyStore extends Store {}
MyStore.prototype.observe = observe;

const store = new Store({
  name: 'world'
});

const { name } = store.get(); // 'world'

store.observe('name', name => {
  console.log(`hello ${name}`);
});  // 'hello world'

store.set({ name: 'everybody' }); // 'hello everybody'
