### ISSUE TITLE
Error location indicator missing if position is 0

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/svelte.technology#41]
If a template is broken right at the start...

```html
</div>
```

...the arrow indicating the location is missing. Add a space at the front and it appears. Must be a type coercion thing

**Comment by Conduitry** [comment]
Something else I noticed, that seems harder to fix, is that if the error is at the end of the file (or just at the end of a line?) the indicator also does not appear. The error indicator mark works by marking the range from the error location through to the next character - and codemirror silently accepts this but does not actually create a mark in the document if it's over an invalid range. This might have to be redone as a codemirror widget or something instead of as a codemirror mark in order to work correctly.
