### ISSUE TITLE
a minor error in documentation

### ISSUE THREAD

**Issue by VenugopalanG** [sveltejs/svelte.technology#416]
Hi,

Firstly, THANKS for Svelte !

In the very well written documentation at 

https://v2.svelte.dev/guide#template-syntax

 in the section that explains "You can access the index of the current element with expression as name, index:'

x and y variables have been swapped in the looping construct creation lines.

Pls fix.

**Comment by Conduitry** [comment]
I would assume that's intentional, and one way of doing it doesn't seem any more right than the other, particularly. (The way it is now, x measures left and right and y measures up and down, which at least matches the cartesian coordinate system, although with y swapped.) If you click through to the [example in the REPL](https://v2.svelte.dev/repl?demo=19g2aa8), you can see that `rows` and `columns` are treated correctly, which seems to be the only objective thing that it needs to get right.

Also do you realize that this is the documentation for Svelte 2 and not Svelte 3?

**Comment by VenugopalanG** [comment]
Thanks for the quick reply.

Agree with you that from a cartesian coordinate system pov, it's quite right and perhaps intentional.

But the conditioned mind when it reads row and column works in a certain way ; 

And thanks for pointing out that I was registering the issue at V2. 

A novice to svelte I am, and still finding my way, like a wide eyed child in the town fair.
