### ISSUE TITLE
Memory leak testing

### ISSUE THREAD

**Issue by northkode** [sveltejs/svelte.technology#6]
Came across your framework and am interested in adding it to my mobile app framework for view rendering.. Curious how much memory leak testing has been done? Considering mobile apparently need a small memory footprint. 

Cheers

**Comment by Rich-Harris** [comment]
We've added Svelte to https://github.com/krausest/js-framework-benchmark, which shows it to have an extremely low memory footprint (lower than anything else I've found) because it has very little book-keeping to do. We don't yet have any automated memory leak tests in place though, agree it would be worthwhile.

**Comment by Rich-Harris** [comment]
Will close this as this is the repo for the https://svelte.technology website, rather than the compiler itself
